name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: prediction_db
      DB_HOST: localhost
      DB_USER_TEST: root
      DB_PASSWORD_TEST: password
      DB_NAME_TEST: prediction_db_test
      DB_HOST_TEST: localhost

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: prediction_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h "127.0.0.1" --protocol=TCP -p"password" && break
            echo "Waiting for MySQL..."
            sleep 2
          done
      - name: Create test database
        run: |
          mysql -h 127.0.0.1 --protocol=TCP -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS $DB_NAME_TEST;"
      - name: Run migrations
        run: npx sequelize db:migrate
      - name: Run tests with SQLite (in-memory)
        env:
          NODE_ENV: test
        run: npm test
      - name: Remove flat ESLint config
        run: rm -f eslint.config.js
      - name: Lint code
        run: |
          npx eslint . --ext .js
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
